# Generated by Django 5.0.2 on 2024-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instagram', '0003_picture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='additional_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
