"""Init

Revision ID: dfe8daccfe2f
Revises: e301fdf805d5
Create Date: 2024-03-24 20:47:38.174898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe8daccfe2f'
down_revision: Union[str, None] = 'e301fdf805d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('name', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('surname', sa.String(), nullable=True))
    op.add_column('owners', sa.Column('birthday', sa.Date(), nullable=True))
    op.create_index(op.f('ix_owners_birthday'), 'owners', ['birthday'], unique=False)
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    op.create_index(op.f('ix_owners_surname'), 'owners', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owners_surname'), table_name='owners')
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_birthday'), table_name='owners')
    op.drop_column('owners', 'birthday')
    op.drop_column('owners', 'surname')
    op.drop_column('owners', 'name')
    # ### end Alembic commands ###
